title: X-LANCE Confernce Deadlines(会议列表)
description: X-LANCE Version of ai-deadlines.es
author: X-LANCE Lab, SJTU

domain: "x-lance.sjtu.edu.cn"
baseurl: "/deadline"

twitter_hashtag: machinelearning
github_username: hsungong
github_repo: ai-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
